# Docker Compose file for self signed ssl nginx server 
#docker run -d --name sql_server -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=someThingComplicated1234' -p 1433:1433 

version: '3.7'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=someThingComplicated1234
    ports:
      - 1433:1433
    #volumes:
    #  - ./certs:/certs
    #  - ./cfg/sample.conf:/etc/nginx/conf.d/sample.conf
